services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "car_parser_app"
      POSTGRES_USER: "anton"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./.db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "anton.agaronov@legalbet.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "80:80"
    volumes:
      - ./pgadmin_data:/pgadmin
    depends_on:
      db:
        condition: service_healthy